# Generated by Django 5.2.1 on 2025-07-15 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
    ]
