# Generated by Django 5.2.1 on 2025-07-15 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0001_initial'),
        ('member', '0001_initial'),
        ('shareMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='group_id',
            field=models.ForeignKey(help_text='그룹 번호', on_delete=django.db.models.deletion.CASCADE, to='shareMain.readinggroup'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='member_id',
            field=models.ForeignKey(help_text='회원 번호', on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.DeleteModel(
            name='GroupChatRoom',
        ),
    ]
