# Generated by Django 5.2.1 on 2025-07-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareMain', '0003_alter_readinggroup_admin_alter_readinggroup_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
