# Generated by Django 5.2.2 on 2025-06-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
