# Generated by Django 5.2.1 on 2025-07-14 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='채팅방 이름 (예: 감성 교환독서 모임)', max_length=255)),
                ('description', models.TextField(help_text='채팅방 설명')),
                ('created_at', models.DateField(auto_now_add=True, help_text='채팅방 생성일시')),
                ('book_title', models.CharField(help_text='책 제목', max_length=255)),
                ('book_author', models.CharField(blank=True, help_text='책 저자 (옵션)', max_length=255, null=True)),
                ('current_members', models.IntegerField(default=0, help_text='현재 참여 인원')),
                ('max_members', models.IntegerField(default=10, help_text='최대 인원')),
                ('profile_image_url', models.URLField(blank=True, help_text='채팅방 프로필 이미지 URL', max_length=500, null=True)),
                ('tags', models.JSONField(default=list, help_text='꼬북태그 (JSON 배열)')),
                ('host', models.ForeignKey(blank=True, help_text='채팅방 개설자', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='내용')),
                ('created_at', models.DateField(auto_now_add=True, help_text='작성일')),
                ('likes', models.IntegerField(default=0, help_text='좋아요 수')),
                ('comments', models.IntegerField(default=0, help_text='댓글 수')),
                ('file', models.ImageField(blank=True, help_text='이미지', null=True, upload_to='chat_files/')),
                ('member_id', models.ForeignKey(help_text='회원 번호', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='부모 메시지 ID (대댓글용)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatrooms.chatmessage')),
                ('group_id', models.ForeignKey(help_text='그룹 번호', on_delete=django.db.models.deletion.CASCADE, to='chatrooms.groupchatroom')),
            ],
        ),
    ]
