# Generated by Django 5.2.1 on 2025-07-09 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booksearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('max_member', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True)),
                ('tag', models.CharField(max_length=50)),
                ('is_public', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booksearch.book')),
            ],
        ),
    ]
