# Generated by Django 5.2.1 on 2025-07-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='is_public',
            field=models.CharField(choices=[('0', '공개'), ('1', '비공개')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
