# Generated by Django 5.2.1 on 2025-07-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_member_id'),
        ('shareMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='member.member'),
            preserve_default=False,
        ),
    ]
