# Generated by Django 5.2.1 on 2025-07-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('member_count', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True)),
                ('book', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('is_public', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
