# Generated by Django 5.2.1 on 2025-07-09 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksearch', '__first__'),
        ('shareMain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readinggroup',
            old_name='member_count',
            new_name='max_member',
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booksearch.book'),
        ),
    ]
