# Generated by Django 5.2.1 on 2025-07-09 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksearch', '0001_initial'),
        ('shareMain', '0002_rename_member_count_readinggroup_max_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksearch.book'),
        ),
    ]
