# Generated by Django 5.2.1 on 2025-07-11 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_member_id'),
        ('shareMain', '0002_alter_readinggroup_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reading_groups', to='member.member'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member_reading_groups', to='member.member'),
        ),
    ]
